---
- name: Restart vpp container
  vars:
    service_name: "vpp"
    service: "{{ vpp_services[service_name] }}"
    config_json: "{{ vpp_config_jsons.results|selectattr('item.key', 'equalto', service_name)|first }}"
    vpp_container: "{{ check_vpp_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    privileged: "{{ service.privileged | default(False) }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - config_json | changed
      or vpp_container | changed

