---
project_name: "vpp"

vpp_services:
  vpp:
    container_name: "vpp"
    image: "{{ vpp_image_full }}"
    enabled: "{{ enable_vpp }}"
    group: vpp
    privileged: True
    host_in_groups: "{{ inventory_hostname in groups['vpp'] }}"
    volumes:
      - "{{ node_config_directory }}/vpp/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
      - "/lib/modules:/lib/modules:ro"
      - "/dev:/dev:rw"
      - "/dev/shm:/dev/shm:rw"
      - "/run:/run:shared"

####################
# Docker
####################
vpp_install_type: "{{ kolla_install_type }}"
vpp_tag: "{{ openstack_release }}"

vpp_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ vpp_install_type }}-vpp"
vpp_image_full: "{{ vpp_image }}:{{ vpp_tag }}"

