---
project_name: "vpp"

vpp_services:
  vpp:
    container_name: "vpp"
    image: "{{ vpp_image_full }}"
    enabled: "{{ enable_vpp }}"
    group: vpp
    host_in_groups: >-
      {{
      inventory_hostname in groups['compute']
      or inventory_hostname in groups['neutron-dhcp-agent']
      or inventory_hostname in groups['neutron-l3-agent']
      or inventory_hostname in groups['neutron-metadata-agent']
      or inventory_hostname in groups['neutron-vpnaas-agent']
      }}
    volumes:
      - "{{ node_config_directory }}/vpp/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run:/run:shared"
      - "kolla_logs:/var/log/kolla/"
      - "/dev/hugepages:/dev/hugepages:rw"

####################
# Docker
####################
vpp_install_type: "{{ kolla_install_type }}"
vpp_tag: "{{ openstack_release }}"

vpp_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ vpp_install_type }}-vpp"
vpp_image_full: "{{ vpp_image }}:{{ vpp_tag }}"

